2020 02 11 file_io.c checkzfile is there a necessarity to copy it?
2020 02 12 get special particals
2020 02 17 smooth 394
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain004.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain005.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain006.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain007.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain008.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain009.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain010.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain011.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain012.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain013.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain014.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain015.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain016.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain017.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain018.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain019.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain020.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain021.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain022.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain023.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain024.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain025.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain026.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain027.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain028.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain029.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain030.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain031.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain032.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain033.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain034.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain035.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain036.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain037.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain038.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain039.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain040.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain041.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain042.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain043.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain044.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain045.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain046.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain047.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain048.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain049.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain050.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain051.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain052.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain053.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain054.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain055.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain056.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain057.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain058.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain059.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain060.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain061.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain062.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain063.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain064.sh;do bash $file;done
for file in /data6/Hao_L/my_specexbin/bash/0910/galaxymain065.sh;do bash $file;done
